Upgrade Ruby and gems
panter/api.panter.ch pull request #15
Opened 2018-10-27 11:11 UTC by toupeira

2018-10-29 10:27 UTC, koffeinfrei requested changes

2018-10-30 09:37 UTC, toupeira commented on Gemfile.lock
> +  revision: 52e5a2895602b6b84840287dbc47ee35e09241c2
Ok switched to the latest release 1.6.1 which seems to work fine and includes the commit 844414849a1c1a9345bb245ade374c9ab89a7463

2018-12-04 15:39 UTC, koffeinfrei approved these changes

2018-12-04 15:40 UTC, koffeinfrei commented
@toupeira I added one more gem update commit

2018-12-06 13:03 UTC, merged

2018-12-06 13:18 UTC, toupeira commented
@koffeinfrei thanks! It's merged and deployed now.